### PR TITLE
Add selectable levels of detail to the 'graph' command

### PR DESCRIPTION
**Pull request by remram44**
This allows to generate graphs that are not too huge to be rendered.

* Processes can be either:
  * Every process and thread
  * Only processes (aggregate threads)
  * Only runs (aggregate all the processes of each run)
* Packages can be either:
  * Every file of every package
  * Aggregate by package
  * Ignore packages (treat every file as an "other file")
* Other files can be either:
  * Every file
  * Only input & output files
  * Not shown

~~The DOT-writing code looks really weird, and should probably be refactored.~~

### CODE REVIEW

**Comment by remram44** [comment]
TODO: actual graphviz style (R/G/B colors are placeholders)

I want to be able to filter out and/or aggregate patterns of files, but this might require work in rpaths.

**Comment by remram44** [comment]
@fchirigati: there is [some doc here](https://github.com/ViDA-NYU/reprozip/blob/graph-levels/docs/graph.rst), you might want to check it out

**Comment by fchirigati** [comment]
Alright, will do later tonight / tomorrow. The plan is to include this in
the official docs?

On Wed, Sep 9, 2015 at 4:46 PM, Remi Rampin <notifications@github.com>
wrote:

> @fchirigati <https://github.com/fchirigati>: there is some doc here
> <https://github.com/ViDA-NYU/reprozip/blob/graph-levels/docs/graph.rst>,
> you might want to check it out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/135#issuecomment-139040949>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
Yes, this is a separate page linked from the "Using reprounzip" page.

**Comment by remram44** [comment]
graph

    reprounzip graph --packages drop --processes thread --otherfiles all \
        --regex-replace '.pyc$' '.py' \
        --regex-filter '^/usr/lib' --regex-filter '^/lib' --regex-filter '^/home/remram/pkgs/ipython/local' --regex-filter '^/home/remram/pkgs/ipython/lib/python2.7' \
        --regex-filter '^/dev' --regex-filter '^/etc/ld.so.cache$' graph.dot digits_sklearn.rpz

**Comment by remram44** [comment]
graph

    graph --packages drop --processes thread --otherfiles io --regex-filter '\.py$' graph.dot digits_sklearn.rpz

**Pull request merged**
