### PR TITLE
added CONTRIBUING.md file

### PR DESCRIPTION
**Pull request by VickySteeves**

### CODE REVIEW

**Comment by VickySteeves** [comment]
I need to fix some stuff. Premature PR. Sorry!

**Comment by remram44** [comment]
You can keep it open :wink:

Also you should follow your own advice and not create PRs from your "master" branch!

**Comment by VickySteeves** [comment]
Where else does a contributing file go besides master?

**Comment by remram44** [comment]
You should send a request to merge from whatever of your branches into ViDA-NYU's master branch 😉

**Pull request closed without merging**
