### PR TITLE
Graph documentation

### PR DESCRIPTION
**Pull request by remram44**

### CODE REVIEW

**Comment by remram44** [comment]
@fchirigati:
> I have just committed my pass. I decided to bring the introduction of reprounzip graph back to unpacking page, and then just leave the command line options as a separate page. Let me know what you think.
> I think it would be nice to say in the command line options page what is the default configuration for reprounzip graph, i.e., when no options are used.

**Comment by remram44** [comment]
I don't know, I kind of liked it being a separate page, since it is a separate task. It might also be augmented with examples (with figures) & recipes...

**Comment by remram44** [comment]
Ok, I moved most stuff back to the graph page, which is in the index under "Visualizing the provenance graph". There are some example figures as well.

**Comment by fchirigati** [comment]
Ok.

Are you done then? Should I give a pass when possible?

On Tue, Sep 15, 2015 at 5:11 PM, Remi Rampin <notifications@github.com>
wrote:

> Ok, I moved most stuff back to the graph page, which is in the index under
> "Visualizing the provenance graph". There are some example figures as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/142#issuecomment-140543559>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
Yes, I am done now

**Comment by fchirigati** [comment]
Done!

PS: I would shift the full provenance graph more to the right so that we
can see at least one run. Or maybe span it a bit more.

On Wed, Sep 16, 2015 at 8:10 AM, Remi Rampin <notifications@github.com>
wrote:

> Yes, I am done now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/142#issuecomment-140722748>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
Better?

**Comment by fchirigati** [comment]
Yes, I like it better now. Thanks!

On Thu, Sep 17, 2015 at 12:48 AM, Remi Rampin <notifications@github.com>
wrote:

> Better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/142#issuecomment-140969558>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Pull request merged**
