### PR TITLE
Add short descriptions for ReproZip releases

### PR DESCRIPTION
**Pull request by remram44**
This makes the news a little more interesting. Is it too much?

### CODE REVIEW

**Comment by VickySteeves** [comment]
I think it looks ok! I wish we could get each item to take up one line :sweat_smile: but it looks good otherwise!

**Comment by VickySteeves** [comment]
Were you planning on adding this to my PR?

**Comment by remram44** [comment]
Made 1.0.7 a tad shorter.

This is easy enough to merge with your changes 😉

**Comment by fchirigati** [comment]
Looks good! I made very few changes just to make the descriptions more consistent.

**Pull request merged**
