### PR TITLE
Changed decoding to UTF-8

### PR DESCRIPTION
**Pull request by Peder2911**
I changed the decoding done in the docker unpacker to UTF-8 from ascii.
The unpacker wasn't working for me until i did this (localization
issue?) Is there any reason not to use UTF-8 decoding ihere?

### CODE REVIEW

**Comment by remram44** [comment]
Hi,

As far as I know, Docker only uses ASCII for image and container IDs. If this is required, it is probably that it read the wrong thing instead of the ID. Do you have a traceback or an example where an error happens?

**Comment by Peder2911** [comment]
Hey! Thank you for the quick reply.

Yep, when trying to do `reprounzip docker run` i get the following traceback:

```
Traceback (most recent call last):
  File "/home/peder/Projects/Blackboxer/venv/bin/reprounzip", line 11, in <module>
    load_entry_point('reprounzip==1.0.16', 'console_scripts', 'reprounzip')()
  File "/home/peder/Projects/Blackboxer/venv/lib/python3.6/site-packages/reprounzip/main.py", line 144, in main
    args.func(args)
  File "/home/peder/Projects/Blackboxer/venv/lib/python3.6/site-packages/reprounzip/unpackers/common/misc.py", line 68, in wrapper
    return func(args)
  File "/home/peder/Projects/Blackboxer/venv/lib/python3.6/site-packages/reprounzip_docker-1.0.16-py3.6.egg/reprounzip/unpackers/docker.py", line 539, in docker_run
    outjson = json.loads(out.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 3163: ordinal not in range(128)
```

The code that i am trying to run is really simple: It's just an R script that outputs a plot of some example data:

```
library(ggplot2)

cars <- read.csv("data/cars.csv")

plt <- ggplot(cars,aes(hp,disp))+
   geom_point()

ggsave("out/plot.png", plt, height = 3, width = 3, device = "png")
```

As i said, it works fine when i change encoding to UTF-8. My system has Norwegian localization, but i can't really see how that would affect docker?

**Comment by Peder2911** [comment]
Same result with a different workflow: Trows same exception, but works after changing the decoding.

**Comment by remram44** [comment]
Ah, it's the JSON! That makes more sense. I forgot that was in there.

**Comment by remram44** [comment]
Thanks for the fix @Peder2911, this `decode()` was incorrect! The JSON output from Docker contains all kinds of things in addition to container/image names.

Hopefully this is always UTF-8 and not locale-dependent, but this is not so easy to test (and who uses something else than UTF-8 nowadays?)

**Comment by Peder2911** [comment]
I am so happy to have been able to contribute to this excellent project. You are doing great work @remram44!

**Pull request merged**
