### PR TITLE
Updated the website look & feel for consistency with rz-examples

### PR DESCRIPTION
**Pull request by VickySteeves**
So I didn't touch very much of the content -- this was mainly a CSS makeover. I also updated the "News" page to use [Bootstrap cards](https://v4-alpha.getbootstrap.com/components/card/) for a better gallery experience, rather than a list.

### CODE REVIEW

**Comment by remram44** [comment]
Needs merge 😅 I can do it tomorrow

**Comment by fchirigati** [comment]
Personally, I like the list better than the cards for presentations, papers, etc, to give a more "professional look"; also, because many presentations and posters are very similar to each other, the images look very repetitive. But I don't have strong feelings against this, so if you guys think cards are better, fine with me ;)

I think the "what's new" part could probably use a better formatting/structure -- I don't like much the original way (my fault -- I wrote this part!). If you think of a better format to present the news, share it with us!

One last thing: when I added the Twitter widget to the page, my main idea was to have it as a sidebar that follows as you scroll up and down, but I never had the chance to try this out. As it is now, the tweets are at the bottom of the page and people may not even see them -- I think the impact would be larger if at the top of the page or as a sidebar. What do you think?

**Comment by remram44** [comment]
I agree that the gallery-style cards take way too much space 😶 And since there are basically multiple versions of the same thing, there is not really a need to show them all.

It's more about showing the places we presented at than the slide decks themselves.

**Comment by fchirigati** [comment]
Thanks, @VickySteeves! I think now the "References" section can be placed below "Examples" as before -- no need to have two columns there.

**Comment by remram44** [comment]
I'm done please check @fchirigati @VickySteeves

**Comment by VickySteeves** [comment]
Looks really great! I love how the navbar goes to "see more" when the window is resized a certain amount, and the twitter bar is static, which is nice. Merge away!

Thanks for all your hard work on this, @remram44 :kiss:

**Comment by fchirigati** [comment]
This looks great, @remram44 ! Thanks for working on this!
PS: I don't see the arrow from "on the original machine" to "on another machine". Is that on purpose?

**Comment by fchirigati** [comment]
And of course, thanks @VickySteeves for working on this as well :)

**Comment by remram44** [comment]
> I don't see the arrow from "on the original machine" to "on another machine". Is that on purpose?

Good catch, fixed by 49154228.

**Pull request merged**
