### PR TITLE
Input/output files and multiple runs

### PR DESCRIPTION
**Pull request by remram44**
The same path can appear multiple times in input/output files, while obviously it can only be replaced by one file's contents.

### CODE REVIEW

**Comment by remram44** [comment]
The VisTrails modules need to know which input/output files to expose as ports; not sure where it should get that from.

**Comment by remram44** [comment]
After discussion:
* We should store which executions are associated with an input/output file. For example:
```yaml
input_files:
- name: config-file
  path: /etc/myconfig
  executions: [1, 4, 8]
```    
With that, we may be able to deduce when running an execution will replace an input file.
This moves the file identification logic out of the vistrails plugin.
* The VisTrails workflow could use a "reprozip pack" type passed from one execution module to another, to represent the unpacked experiment's state. This rids us of the sequencing problem and removes the pesky "directory path" port.

**Comment by remram44** [comment]
This is done, although bugs are to be expected. I have been changing lots of stuff. Also the generated VisTrails workflow is not pretty, but ReproZip has the support to support correct workflows.

**Comment by fchirigati** [comment]
Before releasing 1.0, we need to make sure that most of the bugs are taken
care of. Do you think most of them are covered by the tests?

On Tue, Jul 7, 2015 at 12:37 AM, Remi Rampin <notifications@github.com>
wrote:

> This is done, although bugs are to be expected. I have been changing lots
> of stuff. Also the generated VisTrails workflow is not pretty, but ReproZip
> has the support to support correct workflows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/101#issuecomment-119070724>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
They should be, but it's easy to miss things. Also I might want to add tests with packages generated by older versions (now they always pack and unpack with the current version).

**Comment by fchirigati** [comment]
Right, that's a good idea. Some people have already been using ReproZip, so
they will have packages from previous versions.

On Tue, Jul 7, 2015 at 12:44 AM, Remi Rampin <notifications@github.com>
wrote:

> They should be, but it's easy to miss things. Also I might want to add
> tests with packages generated by older versions (now they always pack and
> unpack with the current version).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/101#issuecomment-119071231>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Pull request merged**
