### PR TITLE
Convenience commands

### PR DESCRIPTION
**Pull request by remram44**
* [x] `download --all` to download all files to the current directory (using their id as filename).
* [x] `download <file>` to download file with id <file> to <file> in the current directory
* [x] ~~`run --all` to run every step~~
* [x] run all runs by default
* [x] Only list input files (or output files) in `showfiles`

### CODE REVIEW

**Comment by remram44** [comment]
I don't like very much `run --all`. In fact it is already available as `run -` (since both ends of the range can be omitted).

Both `--all` commands required changes to the unpackers' code, I should find a more extensible, OOP way of handling plugin's cli.

**Comment by fchirigati** [comment]
> I don't like very much run --all. In fact it is already available as run -
> (since both ends of the range can be omitted).
>
"run -" is not intuitive. What if you run all the packed executions if the
use simply uses "run" (without specifying an id)?


-- 
Sent from Gmail Mobile

**Comment by remram44** [comment]
So basically undo #100?

**Comment by fchirigati** [comment]
It is an alternative to "run --all", so yes. I cannot remember why we
removed this default run ...

On Tue, Feb 2, 2016 at 12:09 PM, Remi Rampin <notifications@github.com>
wrote:

> So basically undo #100 <https://github.com/ViDA-NYU/reprozip/pull/100>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/pull/163#issuecomment-178692835>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
Decision: don't use run --all, make run select all runs by default.

**Pull request merged**
